apiVersion: apps/v1
kind: Deployment
metadata:
  name: elara-deployment
  labels:
    app: elara
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elara
  template:
    metadata:
      labels:
        app: elara
    spec:
      containers:
      - name: elara
        image: elara:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: ALLOWED_HOSTS
          value: "*"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: elara-service
spec:
  selector:
    app: elara
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer