# Generated by Django 5.2.5 on 2025-08-21 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_review_category_is_active_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'session_id', 'timestamp'], name='djangoapp_c_user_id_122287_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('algorithm', models.CharField(max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'score'], name='djangoapp_p_user_id_707009_idx'), models.Index(fields=['created_at'], name='djangoapp_p_created_353e02_idx')],
                'unique_together': {('user', 'product', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'Product View'), ('SEARCH', 'Search Query'), ('ADD_CART', 'Add to Cart'), ('REMOVE_CART', 'Remove from Cart'), ('PURCHASE', 'Purchase'), ('WISHLIST', 'Add to Wishlist'), ('REVIEW', 'Write Review'), ('AI_CHAT', 'AI Assistant Chat')], db_index=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='djangoapp_u_user_id_be5801_idx'), models.Index(fields=['product', 'action'], name='djangoapp_u_product_360e91_idx'), models.Index(fields=['session_id'], name='djangoapp_u_session_fb5c00_idx')],
            },
        ),
    ]
